# Generated by Django 4.2.5 on 2025-10-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True, verbose_name='プロモーションコード')),
                ('discount_amount', models.PositiveIntegerField(verbose_name='割引額')),
                ('is_used', models.BooleanField(default=False, verbose_name='使用済み')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
    ]
