# Generated by Django 4.2.5 on 2025-09-21 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='姓')),
                ('first_name', models.CharField(max_length=50, verbose_name='名')),
                ('user_name', models.CharField(max_length=20, verbose_name='ユーザー名')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('postal_code', models.CharField(max_length=10, verbose_name='郵便番号')),
                ('prefecture', models.CharField(max_length=50, verbose_name='都道府県')),
                ('address_1', models.CharField(max_length=255, verbose_name='市区町村・番地')),
                ('address_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='建物名・部屋番号')),
                ('cc_name', models.CharField(max_length=50, verbose_name='カード名義')),
                ('cc_number', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator('^\\d{13,19}$', '13〜19桁の数字を入力してください')], verbose_name='クレジットカード番号')),
                ('cc_expiration', models.CharField(max_length=5, verbose_name='有効期限(MM/YY)')),
                ('cc_cvv', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{3,4}$', '3又は4桁の数字を入力してください')], verbose_name='セキュリティコード')),
            ],
        ),
    ]
