# Generated by Django 4.2.5 on 2025-09-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_prefecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prefecture',
            field=models.CharField(max_length=10, verbose_name='都道府県'),
        ),
    ]
