# Generated by Django 4.2.5 on 2025-09-22 23:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_prefecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='注文日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='注文金額'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='prefecture',
            field=models.CharField(choices=[('hokkaido', '北海道'), ('aomori', '青森県'), ('iwate', '岩手県'), ('miyagi', '宮城県'), ('akita', '秋田県'), ('yamagata', '山形県'), ('fukushima', '福島県'), ('ibaraki', '茨城県'), ('tochigi', '栃木県'), ('gunma', '群馬県'), ('saitama', '埼玉県'), ('chiba', '千葉県'), ('tokyo', '東京都'), ('kanagawa', '神奈川県'), ('niigata', '新潟県'), ('toyama', '富山県'), ('ishikawa', '石川県'), ('fukui', '福井県'), ('yamanashi', '山梨県'), ('nagano', '長野県'), ('gifu', '岐阜県'), ('shizuoka', '静岡県'), ('aichi', '愛知県'), ('mie', '三重県'), ('shiga', '滋賀県'), ('kyoto', '京都府'), ('osaka', '大阪府'), ('hyogo', '兵庫県'), ('nara', '奈良県'), ('wakayama', '和歌山県'), ('tottori', '鳥取県'), ('shimane', '島根県'), ('okayama', '岡山県'), ('hiroshima', '広島県'), ('yamaguchi', '山口県'), ('tokushima', '徳島県'), ('kagawa', '香川県'), ('ehime', '愛媛県'), ('kochi', '高知県'), ('fukuoka', '福岡県'), ('saga', '佐賀県'), ('nagasaki', '長崎県'), ('kumamoto', '熊本県'), ('oita', '大分県'), ('miyazaki', '宮崎県'), ('kagoshima', '鹿児島県'), ('okinawa', '沖縄県')], max_length=10, verbose_name='都道府県'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('subtotal_price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
            ],
        ),
    ]
