# Generated by Django 4.2.5 on 2025-09-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_created_at_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cc_number',
            field=models.CharField(max_length=19, verbose_name='クレジットカード番号'),
        ),
    ]
