# Generated by Django 4.2.5 on 2025-09-23 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_cc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order', verbose_name='注文名'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.IntegerField(verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_price',
            field=models.IntegerField(verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal_price',
            field=models.IntegerField(verbose_name='小計'),
        ),
    ]
