# Generated by Django 4.2.5 on 2025-10-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_orderitem_product_id_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '未確定'), ('paid', '支払い済み'), ('shipped', '発送済み'), ('cancelled', 'キャンセル')], default='pending', max_length=20),
        ),
    ]
