# Generated by Django 4.2.5 on 2025-10-11 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
