# Generated by Django 4.2.5 on 2025-10-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='割引'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='promo_code',
            field=models.CharField(blank=True, max_length=7, verbose_name='プロモーションコード'),
        ),
    ]
