# Generated by Django 4.2.5 on 2025-11-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_orderitem_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='プロモーションコード'),
        ),
    ]
