# Generated by Django 4.2.5 on 2025-11-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='割引'),
        ),
    ]
