# Generated by Django 4.2.5 on 2025-09-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_created_at_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
